### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'bibles/json-bibles/akjv.json.pbz2'

### ISSUE THREAD

**Issue by ruxlin** [samhaswon/selfhosted-bible#31]
Thanks so much for such a wonderful app. I am getting the following error in the docker logs:

FileNotFoundError: [Errno 2] No such file or directory: 'bibles/json-bibles/akjv.json.pbz2'

FileNotFoundError: [Errno 2] No such file or directory: 'bibles/json-bibles/akjv.json.pbz2' that is the reason, I cannot access the webui.

**Comment by samhaswon** [comment]
Should be fixed now.
