### ISSUE TITLE
Dark mode & split version windows

### ISSUE THREAD

**Issue by ruxlin** [samhaswon/selfhosted-bible#37]
Thanks so much for this app..really useful for my bible studies. Grateful to advise how I can switch to 'Dark mode' and also split windows. Be blessed.

**Comment by samhaswon** [comment]
Split version reading can be done by selecting multiple versions using `Ctrl + Click` on the versions you wish to open. 

As for dark mode, that is solely based on browser preference. Except for the favicon for some reason, as that is based on the OS 🤷‍♂️. I might add a toggle later, but I will need some time to find a good way to do that across browsers. That can either involve JS + CSS or rewriting how the reading page works to fetch content. I don't currently know of a good way to make the selection stateful without the page flashing.
